services:
  srok:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TARGETPLATFORM=${TARGET}
    container_name: srok
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 3000:3000