/*
 * GitHub Commit Search
 *
 * Minimal spec exposing only the /search/commits endpoint from GitHub v3 REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthorSummary {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
}

impl AuthorSummary {
    pub fn new() -> AuthorSummary {
        AuthorSummary {
            name: None,
            email: None,
            date: None,
        }
    }
}
