/*
 * GitHub Commit Search
 *
 * Minimal spec exposing only the /search/commits endpoint from GitHub v3 REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::services::github::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommitDetail {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "author")]
    pub author: Box<models::AuthorSummary>,
}

impl CommitDetail {
    pub fn new(message: String, author: models::AuthorSummary) -> CommitDetail {
        CommitDetail {
            message,
            author: Box::new(author),
        }
    }
}
