/*
 * GitHub Commit Search
 *
 * Minimal spec exposing only the /search/commits endpoint from GitHub v3 REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::services::github::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommitSearchResponse {
    #[serde(rename = "total_count")]
    pub total_count: i32,
    #[serde(rename = "incomplete_results")]
    pub incomplete_results: bool,
    #[serde(rename = "items")]
    pub items: Vec<models::CommitItem>,
}

impl CommitSearchResponse {
    pub fn new(
        total_count: i32,
        incomplete_results: bool,
        items: Vec<models::CommitItem>,
    ) -> CommitSearchResponse {
        CommitSearchResponse {
            total_count,
            incomplete_results,
            items,
        }
    }
}
