replicaCount: 1

image:
  repository: mikeengineering/srok
  pullPolicy: Always
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 3000

env:
  - name: SHODAN_API_KEY
    valueFrom:
      secretKeyRef:
        name: srok-secret
        key: shodan-api-key
  - name: GITHUB_TOKEN
    valueFrom:
      secretKeyRef:
        name: srok-secret
        key: github-token
  - name: ORIGIN_BASE_URL
    value: "https://srok.mikejoseph.org"

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: srok.mikejoseph.org
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: cloudflare-origin-cert
     hosts:
       - srok.mikejoseph.org

resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 500m
    memory: 512Mi

livenessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 3
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 3
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3
  successThreshold: 1

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations:
  - key: "kubernetes.azure.com/scalesetpriority"
    operator: "Equal"
    value: "spot"
    effect: "NoSchedule"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.azure.com/scalesetpriority
          operator: In
          values:
          - spot
